name: 'Publish branch to npm'
description: 'Publish a pre-release version of an npm package to the registry'
author: 'Wistia Engineering'

inputs:
  github_token:
    description: 'GitHub authorization token'
    required: true
  npm_token:
    description: 'npm authorization token'
    required: true
  commit_hash:
    description: 'SHA-1 hash of the commit to publish'
    required: true
    default: '${{ github.event.pull_request.head.sha }}'
  dry_run:
    description: 'If true, will run action normally except it will not publish anything to npm'
    required: false
    default: 'false'

runs:
  using: 'node20'
  main: 'dist/index.mjs'

branding:
  icon: package
  color: red
