name: Lint

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Check out Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Parse .tool-versions
        uses: wistia/parse-tool-versions@9b83f64a97423b071339ef0906937177701c1bba # v1.0

      - name: Set up Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ env.NODEJS_TOOL_VERSION }}

      - name: Cache node_modules
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node${{ env.NODEJS_TOOL_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node${{ env.NODEJS_TOOL_VERSION }}-

      - name: Install Node.js dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Oxlint
        run: npm run lint:ci

      - name: Run oxfmt
        run: npm run format:ci
